name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add clippy
      - run: cargo clippy --all-features
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  cargo-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo doc
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo test --all-features
